spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: FUYAWEB
    password: 1314
    driver-class-name: oracle.jdbc.driver.OracleDriver
  data:
    solr:
      host: http://192.168.80.128:8080/solr/new_core
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  devtools:
    restart:
      enabled: true
     # additional-paths: src/main/java
      exclude: WEB-INF/**
  redis:
    expireSeconds: 120
    clusterNodes: 192.168.80.128:6661,192.168.80.128:6662,192.168.80.128:6663,192.168.80.128:6664,192.168.80.128:6665,192.168.80.128:6666
    jedis:
      pool:
        max-active: 300
       # maxwait: 100
        min-idle: 100
    database: 0
    commandTimeout: 10000
    password: 1314
  activemq:
    broker-url: tcp://192.168.80.128:61616
    pool:
      enabled: false
    in-memory: true
    password: admin
    user: admin
  jms:
    pub-sub-domain: true
server:
  port: 8063





